### ISSUE TITLE
Octagon SFX6018

### ISSUE THREAD

**Issue by Ciksa** [openhdf/hdfradio#1]
I tried to install the latest version of the plugin enigma2-plugin-extensions-hdfradio_1.23.1_py3_3.11.2_arm.ipk on an ARM box Octagon SFX6018 with OpenATV 7.4 and python 3.11.2 and it says:
Not selecting enigma2-plugin-extensions-hdfradio 1.23.1+git212+eb8a026 due to incompatible architecture.

The last that can be installed there and is functional is the version enigma2-plugin-extensions-hdfradio_1.21.1_py3_3.11.0_all.ipk

**Comment by koivo** [comment]
Different arm chipsets. We are working on a solution.

**Comment by koivo** [comment]
as i say
